# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_first.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5 import QtCore, QtGui, QtWidgets


class login(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(864, 491)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(300, 370, 93, 35))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("background-color:white;border-radius: 10px;border: 3px solid blue;")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 370, 93, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet("background-color:white;border-radius: 10px;border: 3px solid blue;")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(260, 60, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(250, 200, 341, 111))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.radiobtn1 = QtWidgets.QRadioButton(Dialog)
        self.radiobtn1.setGeometry(QtCore.QRect(330,300,100,40))
        self.radiobtn1.setText('用户')
        self.radiobtn1.setStyleSheet("color:blue;")
        self.radiobtn1.setChecked(True)

        self.radiobtn2 = QtWidgets.QRadioButton(Dialog)
        self.radiobtn2.setGeometry(QtCore.QRect(450, 300, 100, 40))
        self.radiobtn2.setText('管理员')
        self.radiobtn2.setStyleSheet("color:blue;")

        self.pushButton_2.clicked.connect(Dialog.login_in)
        self.pushButton.clicked.connect(Dialog.login_main)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "病虫害识别平台"))
        self.pushButton.setText(_translate("Dialog", "登录"))
        self.pushButton_2.setText(_translate("Dialog", "注册"))
        self.label_3.setText(_translate("Dialog", "病虫害识别平台"))
        self.label_3.setStyleSheet("font-weight:bold;color:blue;")
        self.label.setText(_translate("Dialog", "账号"))
        self.label.setStyleSheet("font-weight:bold;color:blue;")
        self.label_2.setText(_translate("Dialog", "姓名"))
        self.label_2.setStyleSheet("font-weight:bold;color:blue;")

        Dialog.setStyleSheet("#Dialog{border-image:url(Pic/R-C.jpg)}")

