# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *

class Manager(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1133, 641)

        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(390,140,541,311))
        self.model = QStandardItemModel()
        self.model.setHorizontalHeaderLabels(['用户名', '密码'])
        self.tableView.setModel(self.model)
        self.tableView.setSelectionBehavior(QAbstractItemView.SelectRows)  # 设置只能选中整行
        self.tableView.setSelectionMode(QAbstractItemView.SingleSelection)  # 设置只能选中一行
        self.tableView.setStyleSheet('background-color:white;')
        self.tableView.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)

        self.btn1 = QtWidgets.QPushButton(Dialog)
        self.btn1.setGeometry(QtCore.QRect(500,490,93,40))
        self.btn1.setText('保存修改')
        self.btn1.setStyleSheet("border-radius: 15px;border: 3px solid blue;")
        self.btn1.clicked.connect(Dialog.save)
        self.btn2 = QtWidgets.QPushButton(Dialog)
        self.btn2.setGeometry(QtCore.QRect(720, 490, 93, 40))
        self.btn2.setText('删除信息')
        self.btn2.clicked.connect(Dialog.delete)
        self.btn2.setStyleSheet("border-radius: 15px;border: 3px solid blue;")

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(490, 0, 171, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1131, 91))
        self.label_2.setStyleSheet("background-color:rgb(85, 85, 85);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 120, 151, 40))
        self.pushButton.setStyleSheet("border-radius:5px;font: 14pt \'微软雅黑\';font-weight:bold;border:3px solid rgb(184,184,184);background-color: rgb(184, 184, 184);color: rgb(56,56,56);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 330, 151, 40))
        self.pushButton_2.setStyleSheet("border-radius:5px;font: 14pt \'微软雅黑\';font-weight:bold;border:3px solid rgb(184,184,184);background-color: rgb(184, 184, 184);color: rgb(56,56,56);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 90, 211, 551))
        self.label_3.setStyleSheet("background-color:gray;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 540, 151, 40))
        self.pushButton_3.setStyleSheet("border-radius:5px;font: 14pt \'微软雅黑\';font-weight:bold;border:3px solid rgb(184,184,184);background-color: rgb(184, 184, 184);color: rgb(56,56,56);")
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 190, 151, 40))
        self.pushButton_8.setStyleSheet(
            "border-radius:5px;font: 14pt \'微软雅黑\';font-weight:bold;border:3px solid rgb(184,184,184);background-color: rgb(184, 184, 184);color: rgb(56,56,56);")
        self.pushButton_8.clicked.connect(Dialog.hide4)

        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 260, 151, 40))
        self.pushButton_9.setStyleSheet(
            "border-radius:5px;font: 14pt \'微软雅黑\';font-weight:bold;border:3px solid rgb(184,184,184);background-color: rgb(184, 184, 184);color: rgb(56,56,56);")
        self.pushButton_9.clicked.connect(Dialog.hide5)


        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 400, 151, 40))
        self.pushButton_10.setStyleSheet(
            "border-radius:5px;font: 14pt \'微软雅黑\';font-weight:bold;border:3px solid rgb(184,184,184);background-color: rgb(184, 184, 184);color: rgb(56,56,56);")
        self.pushButton_10.clicked.connect(Dialog.hide6)


        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(30, 470, 151, 40))
        self.pushButton_11.setStyleSheet(
            "border-radius:5px;font: 14pt \'微软雅黑\';font-weight:bold;border:3px solid rgb(184,184,184);background-color: rgb(184, 184, 184);color: rgb(56,56,56);")
        self.pushButton_11.clicked.connect(Dialog.hide7)


        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setStyleSheet("border:1px solid black;")
        self.label_4.setGeometry(QtCore.QRect(430,150,441,351))

        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setText("默认模型")
        self.label_5.setGeometry(QtCore.QRect(492,192,90,40))

        self.combox = QtWidgets.QComboBox(Dialog)
        self.combox.setGeometry(QtCore.QRect(589,192,170,40))

        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setText("iou_thres")
        self.label_6.setGeometry(QtCore.QRect(492,291,90,40))

        self.lineEdit1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit1.setGeometry(QtCore.QRect(589,291,171,40))

        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setText("conf_thres")
        self.label_7.setGeometry(QtCore.QRect(492,389,90,40))

        self.lineEdit2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit2.setGeometry(QtCore.QRect(589,389,171,40))

        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(790,540,93,40))
        self.pushButton_4.setStyleSheet("border-radius: 15px;border: 3px solid blue;")
        self.pushButton_4.setText("保存修改")
        self.pushButton_4.clicked.connect(Dialog.save_trans)

        self.pushQuit = QtWidgets.QPushButton(Dialog)
        self.pushQuit.setGeometry(QtCore.QRect(990,30,93,28))
        self.pushQuit.setText("退出登录")
        # self.pushQuit.setStyleSheet("background-color:blue;")
        self.pushQuit.clicked.connect(Dialog.exit_login)

        font = QtGui.QFont()
        font.setFamily('华文行楷')
        font.setBold(True)

        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(470,180,72,21))
        self.label_8.setText("账号：")
        self.label_8.setFont(font)
        self.lineEdit3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit3.setGeometry(QtCore.QRect(520,174,113,28))
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(660,181,72,21))
        self.label_9.setText("姓名：")
        self.label_9.setFont(font)
        self.lineEdit4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit4.setGeometry(QtCore.QRect(709,174,113,28))
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(470,226,72,15))
        self.label_10.setText("反馈内容：")
        self.label_10.setFont(font)
        self.TextEdit = QtWidgets.QTextEdit(Dialog)
        self.TextEdit.setGeometry(QtCore.QRect(470,260,411,100))
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(470, 366, 72, 15))
        self.label_11.setText("回馈：")
        self.label_11.setFont(font)
        self.TextEdit_1 = QtWidgets.QTextEdit(Dialog)
        self.TextEdit_1.setGeometry(QtCore.QRect(470, 390, 411, 100))
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(300,250,41,221))
        self.pushButton_5.setStyleSheet("QPushButton{border-image: url(./Pic/左移.png)};")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(970, 250, 41, 221))
        self.pushButton_6.setStyleSheet("QPushButton{border-image: url(./Pic/右移.png)};")

        self.pushButton_5.clicked.connect(Dialog.trans_left)
        self.pushButton_6.clicked.connect(Dialog.trans_right)

        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(780, 520, 93,40))
        self.pushButton_7.setStyleSheet("border-radius: 15px;border: 3px solid blue;")
        self.pushButton_7.setText('发送回馈')
        self.pushButton_7.clicked.connect(Dialog.send_ret)


        # 害虫信息管理
        self.tableView1 = QtWidgets.QTableView(Dialog)
        self.tableView1.setGeometry(QtCore.QRect(390, 140, 541, 311))
        self.model1 = QStandardItemModel()
        self.model1.setHorizontalHeaderLabels(['害虫名称'])
        self.tableView1.setModel(self.model1)
        self.tableView1.setSelectionBehavior(QAbstractItemView.SelectRows)  # 设置只能选中整行
        self.tableView1.setSelectionMode(QAbstractItemView.SingleSelection)  # 设置只能选中一行
        self.tableView1.setStyleSheet('background-color:white;')
        self.tableView1.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.pushButton_20 = QtWidgets.QPushButton(Dialog)
        self.pushButton_20.setGeometry(QtCore.QRect(480, 500, 90, 38))
        self.pushButton_20.setText("添加")
        self.pushButton_21 = QtWidgets.QPushButton(Dialog)
        self.pushButton_21.setGeometry(QtCore.QRect(720, 500, 90, 38))
        self.pushButton_21.setText("删除")



        fontshibie = QtGui.QFont()
        fontshibie.setPointSize(14)


        # 识别模式
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setGeometry(QtCore.QRect(430,210,161,61))
        self.label_30.setText('图片识别功能')
        self.label_30.setFont(fontshibie)
        self.label_31 = QtWidgets.QLabel(Dialog)
        self.label_31.setGeometry(QtCore.QRect(430, 300, 161, 61))
        self.label_31.setText('摄像头识别功能')
        self.label_31.setFont(fontshibie)
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setGeometry(QtCore.QRect(430, 390, 161, 61))
        self.label_32.setText('视频识别功能')
        self.label_32.setFont(fontshibie)
        self.pushButton_30 = QtWidgets.QPushButton(Dialog)
        self.pushButton_30.setGeometry(QtCore.QRect(650,220,93,38))
        self.pushButton_30.setText('禁用')
        self.pushButton_31 = QtWidgets.QPushButton(Dialog)
        self.pushButton_31.setGeometry(QtCore.QRect(650, 310, 93, 38))
        self.pushButton_31.setText('禁用')
        self.pushButton_32 = QtWidgets.QPushButton(Dialog)
        self.pushButton_32.setGeometry(QtCore.QRect(650, 400, 93, 38))
        self.pushButton_32.setText('禁用')
        self.pushButton_33 = QtWidgets.QPushButton(Dialog)
        self.pushButton_33.setGeometry(QtCore.QRect(770, 220, 93, 38))
        self.pushButton_33.setText('启用')
        self.pushButton_34 = QtWidgets.QPushButton(Dialog)
        self.pushButton_34.setGeometry(QtCore.QRect(770, 310, 93, 38))
        self.pushButton_34.setText('启用')
        self.pushButton_35 = QtWidgets.QPushButton(Dialog)
        self.pushButton_35.setGeometry(QtCore.QRect(770, 400, 93, 38))
        self.pushButton_35.setText('启用')

        # 识别结果管理
        fontresult = QFont()
        fontresult.setPointSize(14)
        self.label_40 = QtWidgets.QLabel(Dialog)
        self.label_40.setGeometry(QtCore.QRect(390,200,211,91))
        self.label_40.setText('图片识别结果输出')
        self.label_40.setFont(fontresult)
        self.label_41 = QtWidgets.QLabel(Dialog)
        self.label_41.setGeometry(QtCore.QRect(390, 280, 211, 91))
        self.label_41.setText('图片识别结果输出')
        self.label_41.setFont(fontresult)
        self.label_42 = QtWidgets.QLabel(Dialog)
        self.label_42.setGeometry(QtCore.QRect(390, 360, 211, 91))
        self.label_42.setText('图片识别结果输出')
        self.label_42.setFont(fontresult)
        self.pushButton_40 = QtWidgets.QPushButton(Dialog)
        self.pushButton_40.setGeometry(QtCore.QRect(630,230,93,35))
        self.pushButton_40.setText('禁用')
        self.pushButton_41 = QtWidgets.QPushButton(Dialog)
        self.pushButton_41.setGeometry(QtCore.QRect(630, 310, 93, 35))
        self.pushButton_41.setText('禁用')
        self.pushButton_42 = QtWidgets.QPushButton(Dialog)
        self.pushButton_42.setGeometry(QtCore.QRect(630, 390, 93, 35))
        self.pushButton_42.setText('禁用')
        self.pushButton_43 = QtWidgets.QPushButton(Dialog)
        self.pushButton_43.setGeometry(QtCore.QRect(750, 230, 93, 35))
        self.pushButton_43.setText('启用')
        self.pushButton_44 = QtWidgets.QPushButton(Dialog)
        self.pushButton_44.setGeometry(QtCore.QRect(750, 310, 93, 35))
        self.pushButton_44.setText('启用')
        self.pushButton_45 = QtWidgets.QPushButton(Dialog)
        self.pushButton_45.setGeometry(QtCore.QRect(750, 390, 93, 35))
        self.pushButton_45.setText('启用')


        # 讨论区管理
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(280, 100, 800, 501))
        self.scrollArea.setMinimumSize(QtCore.QSize(700, 400))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 750, 10000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(800, 10000))

        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(90, 60, 791, 351))
        self.widget.setObjectName("widget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)


        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()

        self.pushQuit.raise_()

        self.pushButton.clicked.connect(Dialog.hide1)
        self.pushButton_2.clicked.connect(Dialog.hide2)
        self.pushButton_3.clicked.connect(Dialog.hide3)

        Dialog.hide1()


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "病虫害识别平台——管理员模式"))
        self.label.setText(_translate("Dialog", "管理员"))
        self.pushButton.setText(_translate("Dialog", "用户管理"))
        self.pushButton_2.setText(_translate("Dialog", "识别参数管理"))
        self.pushButton_3.setText(_translate("Dialog", "反馈消息"))
        self.pushButton_8.setText(_translate("Dialog", "害虫信息管理"))
        self.pushButton_9.setText(_translate("Dialog", "识别模式管理"))
        self.pushButton_10.setText(_translate("Dialog", "识别结果管理"))
        self.pushButton_11.setText(_translate("Dialog", "讨论区管理"))
